# theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Delia Li - Technical Writer

description: Welcome to my technical writing portfolio! Thank you for taking the time to review my work samples.